apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb
    type: postgres
    access: proxy
    isDefault: true
    editable: false
    url: ${GRAFANA_POSTGRES_HOST}
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      postgresVersion: 1800
      sslmode: disable
