{
 "title": "Satellite",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Current Voltage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "space",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value AS \"Voltage\"\r\nFROM telemetry\r\nWHERE satellite_id = 1 AND metric_id = 1\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "space",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value AS \"Temperature\"\r\nFROM telemetry\r\nWHERE satellite_id = 1 AND metric_id = 2\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Last Contact",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "space",
     "rawSql": "SELECT\r\n  MAX(timestamp) AS \"time\",\r\n  EXTRACT(EPOCH FROM (NOW() - MAX(timestamp))) AS \"Seconds Ago\"\r\nFROM telemetry\r\nWHERE satellite_id = 1"
    }
   ]
  },
  {
   "title": "Solar Panel Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "dataset": "space",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value AS \"Temperature (°C)\"\r\nFROM telemetry\r\nWHERE\r\n  satellite_id = 1\r\n  AND metric_id = 2\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "dataset": "space",
     "rawSql": "SELECT\r\n  timestamp AS \"time\",\r\n  value AS \"Voltage (V)\"\r\nFROM telemetry\r\nWHERE\r\n  satellite_id = 1\r\n  AND metric_id = 1\r\n  AND $__timeFilter(timestamp)\r\nORDER BY timestamp;"
    }
   ]
  }
 ]
}